First DNA with UI RAD
holochain/RAD-Tools-Phase-2 pull request #5
Opened 2020-04-30 16:33 UTC by JettTech

2020-05-04 19:24 UTC, zo-el requested changes
Not reviewed everything, this is just the first run of reviewing.
I think we need to rename `setup` to `src` and remove `dna-src`. it should be gitignored right?

Also we need to give a link or notes of how to create a `sample-type-spec.json` file.

2020-05-04 19:24 UTC, zo-el commented on conductor-config.example.toml
> +sim2h_url = "ws://public.sim2h.net:9000"
Please use localhost here

2020-05-05 19:04 UTC, JettTech commented
Yes, they should be ignored.  Sorry for the massive file overload.  I removed the files and add ui-src and dna-src to the .gitignore.

2020-05-07 20:41 UTC, zo-el requested changes
### Review: (These are just overview questions and thoughts)
- Why is the agent-setup and type-spec still in set up? it should all be inside the src. All the code should be inside src
- Read me needs to be updated
- Cool Hint to notify that you may not be running in nix-shell. Later we could probably change the color of the Hint to Yellow or something
- Why don't we implement a way to refer you own path?
- So we are only generating one zome right?
-  Can we write some comments later on the code. Not everywhere but in places like when your reading the sample-type-spec, it would help the reader() not very important.

### Code Review: 
- **BUG needs attention:** The `default.nix` file that is generated by `hc init` (I am assuming) points to a very old release of holochain. (` holonix-release-tag = "further-bad-assigning";`) this needs to be updated

2020-05-07 20:48 UTC, JettTech commented
@joel 
 - Why is the agent-setup and type-spec still in setup? it should all be inside the src. All the code should be inside src/
    - The setup folder will remain in the user's own app directory when using the holonix tool for optional continued use, while the code generation src will be removed. 
     >NB: I decided to keep it inside a separate setup directory, but place that directory as a sub-directory in the src folder. Open to thoughts on this.

 - Read me needs to be updated 
    -  :+1: This is a next todo.

 - Cool Hint to notify that you may not be running in nix-shell. Later we could probably change the color of the Hint to Yellow or something
    - Good idea.  I decided to import and use Chalk. 

 - Why don't we implement a way to refer your own path?
    -  Agreed and implemented.

 - So we are only generating one zome right?
   - The code can generate multiple, but only one is required.

 - Can we write some comments later on the code. Not everywhere but in places like when you're reading the sample-type-spec, it would help the reader() not very important of course
   - Can you name the places that stood out to you? :question:

2020-05-12 15:40 UTC, robbiecarlton requested changes
Adding a second type to a single zome is currently broken. I get an error
```
Holochain Instance Error: Zome function 'create_post' not found in Zome 'users'
```
when trying to call `create` on my second type.

I'm also getting a validation error on my first type but that might be user error.

2020-05-12 15:40 UTC, robbiecarlton commented on package.json
> +    "hc:start": "holochain -c conductor-config.toml &> conductor.log &",
It's a little awkward that this hides its output. It means it fails silently when you haven't generated a conductor. We could add a check to this command that returns an error if there's no conductor, saying "try running hc:generate-conductor first".

But actually I think it's better to not send the output to a log file. Let the user do that if they want.

2020-05-12 15:40 UTC, robbiecarlton commented on src/setup/type-specs/sample-type-spec.json
> +  "types": {
this file should have two types defined in it. Having two types in this one zome doesn't currently work.

2020-05-15 16:30 UTC, robbiecarlton approved these changes

2020-05-15 16:30 UTC, robbiecarlton commented on README.md
> +    $ npm run hc:generate-conductor
remove this step

2020-05-15 16:30 UTC, robbiecarlton commented on README.md
> +    ```
add a brief description/example of the json

2020-05-15 16:30 UTC, robbiecarlton commented on README.md
> +$ cd Holochain
move this to a Readme in Holonix

2020-05-15 16:30 UTC, robbiecarlton commented on src/dna-setup/scripts/generate-dna-zomes.js
> +const renderZomeCargoToml = (zomeName, zomeDir) => {
if it writes the file, we call it `generate`. If it just returns the content to be written, we call it `render`

2020-05-15 16:30 UTC, robbiecarlton commented on src/dna-setup/scripts/generate-dna-zomes.js
> +const renderNixSetup = (dnaName, zomeDir) => {
`generateNixSetup`

2020-05-15 16:30 UTC, robbiecarlton commented on src/setup/type-specs/sample-type-spec.json
> +        "list": true
do we currently support this?

2020-05-15 17:25 UTC, merged

2020-05-15 17:25 UTC, JettTech commented on src/setup/type-specs/sample-type-spec.json
> +        "list": true
The DNA does - I'll move it to that section of the readme.the DNA does - I'll move it to that section of the readme.

2020-05-15 17:26 UTC, JettTech commented on src/dna-setup/scripts/generate-dna-zomes.js
> +const renderNixSetup = (dnaName, zomeDir) => {
I like the naming distinction.